app/rtshare/rtshare/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import authenticate
from django.contrib import admin
from django.urls import path, include
import django_eventstream


def events(request, **kwargs):
    if user := authenticate(request):
        request.user = user
    return django_eventstream.views.events(request, **kwargs)


urlpatterns = [
    path('', include('observations.urls')),
    path('', include('public.urls')),
    path('', include('telescope.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api/events/<channel>', events, name='event-stream'),
    path(
        'stream/events/',
        django_eventstream.views.events,
        name='multi-event-stream',
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/rtshare/telescope/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # Site Views

    path(
        'telescopes/',
        views.TelescopeListView.as_view(),
        name='telescope.list',
    ),
    path(
        'telescopes/<int:pk>/',
        views.TelescopeDetailView.as_view(),
        name='telescope.update',
    ),
    path(
        'telescopes/<int:pk>/ping',
        views.TelescopeSendPingEventView.as_view(),
        name='telescope.ping',
    ),
    path(
        'telescopes/<int:pk>/reconfigure',
        views.TelescopeSendReconfigureEventView.as_view(),
        name='telescope.reconfigure',
    ),
    path(
        'telescopes/<int:pk>/observations',
        views.TelescopeObservationListView.as_view(),
        name='telescope.observation-list',
    ),

    # API Views

    path(
        'api/telescope/<int:pk>/health-check',
        views.TelescopeHealthCheckView.as_view(),
        name='telescope.health-check',
    ),
    path(
        'api/telescope/<int:pk>/tasks',
        views.TelescopeAPIView.as_view(),
        name='telescope.tasks',
    ),
    path(
        'api/telescope/<int:pk>/transmit',
        views.SampleDataTransmitView.as_view(),
        name='observation.transmit',
    ),
]

app/rtshare/users/urls.py
from django.urls import path

from . import views


urlpatterns = [
    # Site Views

    path(
        'users/<int:pk>/events/',
        views.UserEventsListView.as_view(),
        name='user.events-list',
    ),

    path(
        'users/<int:pk>/',
        views.AccountView.as_view(),
        name='user.account',
    ),
]

app/rtshare/observations/models.py
from datetime import timedelta

from django.conf import settings
from django.core.files.storage import storages
from django.core.validators import MaxValueValidator
from django.db import models
from django.utils import timezone

from rtshare.utils.models import BaseModel
from rtshare.utils.units import display_hz


def get_storage():
    return (
        storages['default']
        if settings.DEBUG else
        storages['remote']
    )


class Sample(BaseModel):

    observation = models.ForeignKey(
        'observations.Observation',
        related_name='samples',
        on_delete=models.CASCADE,
    )

    telescope = models.ForeignKey(
        'telescope.Telescope',
        related_name='samples',
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
    )

    configuration = models.ForeignKey(
        'observations.Configuration',
        related_name='samples',
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
    )

    frequency = models.PositiveBigIntegerField(
        default=None,
        null=True,
        blank=True,
        help_text=(
            'The center frequency that was captured (in Hz).'
        )
    )

    sample_rate = models.PositiveBigIntegerField(
        default=None,
        null=True,
        blank=True,
        help_text=(
            'The sample rate at which data was collected.'
        )
    )

    sample_size = models.PositiveBigIntegerField(
        default=None,
        null=True,
        blank=True,
        help_text=(
            'The number of samples in the record.'
        )
    )

    ppm = models.PositiveSmallIntegerField(
        default=None,
        null=True,
        blank=True,
        help_text=(
            'The PPM offset used for the device (0 is none).'
        )
    )

    gain = models.PositiveSmallIntegerField(
        default=None,
        null=True,
        blank=True,
        validators=[
            MaxValueValidator(100),
        ],
        help_text=(
            'The amount of gain applied to the SDR.'
        )
    )

    captured_at = models.DateTimeField(
        default=None,
        null=True,
        blank=True,
        help_text=(
            'The timestamp when the data was collected.'
        )
    )

    data = models.FileField(
        storage=get_storage(),
        upload_to='starsweep/data/'
    )

    class Meta:
        ordering = ('-id',)


class Configuration(BaseModel):

    class ProcessingState:
        IN_PROGRESS = 'in-progress'
        ERROR = 'error'
        COMPLETE = 'complete'

        choices = (
            (IN_PROGRESS, 'In Progress'),
            (ERROR, 'Error'),
            (COMPLETE, 'Complete'),
        )

    name = models.CharField(
        max_length=256,
        help_text=(
            'The human-recognizable name for the observation configuration.'
        )
    )

    observation = models.ForeignKey(
        'observations.Observation',
        related_name='configurations',
        on_delete=models.CASCADE,
    )

    processing_state = models.CharField(
        max_length=12,
        choices=ProcessingState.choices,
        blank=True,
        null=True,
        help_text=(
            'The current state of the analysis for this configuration data.'
        )
    )

    frequency = models.PositiveBigIntegerField(
        default=89_500_000,
        help_text=(
            'The center frequency to capture (in Hz).'
        )
    )

    sample_rate = models.PositiveBigIntegerField(
        default=2_048_000,
        help_text=(
            'The sample rate at which to collect data.'
        )
    )

    sample_size = models.PositiveBigIntegerField(
        default=1_024,
        help_text=(
            'How many data points to collect per sample.'
        )
    )

    ppm = models.PositiveSmallIntegerField(
        default=0,
        help_text=(
            'What PPM offset to use for the device (0 is none).'
        )
    )

    gain = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(100),
        ],
        help_text=(
            'The amount of gain to apply via the SDR.'
        )
    )

    class Meta:
        ordering = ('-id',)

    def get_identifier(self, telescope):
        return f'{telescope.id}-{self.observation.id}-{self.id}'

    def parse_identifier(self, identifier):
        return identifier.split('-')

    @property
    def hz(self):
        return display_hz(self.frequency)

    def is_complete(self):
        return self.processing_state == self.ProcessingState.COMPLETE

    def is_error(self):
        return self.processing_state == self.ProcessingState.ERROR


class Observation(BaseModel):

    name = models.CharField(
        max_length=256,
        help_text=(
            'The human-recognizable name for the device.'
        )
    )

    telescopes = models.ManyToManyField(
        'telescope.Telescope',
        related_name='observations',
        help_text=(
            'The telescopes that are involved in the observation and collection of data.'
        )
    )

    # Observation Configuration Fields

    start_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text=(
            'When the given observation should begin?'
        )
    )

    end_at = models.DateTimeField(
        blank=True,
        null=True,
        help_text=(
            'When the given observation should begin?'
        )
    )

#     azimuth_degrees = models.DecimalField(
#         max_digits=8,
#         decimal_places=5,
#         blank=True,
#         null=True,
#         default=None,
#     )
#
#     elevation_degrees = models.DecimalField(
#         max_digits=8,
#         decimal_places=5,
#         blank=True,
#         null=True,
#         default=None,
#     )
#
#     right_ascention_degrees = models.DecimalField(
#         max_digits=10,
#         decimal_places=7,
#         blank=True,
#         null=True,
#         default=None,
#     )
#
#     declination_degrees = models.DecimalField(
#         max_digits=10,
#         decimal_places=7,
#         blank=True,
#         null=True,
#         default=None,
#     )

    class Meta:
        ordering = ('-start_at', '-end_at')

#     @property
#     def is_celestial(self):
#         return self.right_ascention_degrees and self.declination_degrees
#
#     @property
#     def is_local(self):
#         return self.azimuth_degrees and self.elevation_degrees

    @property
    def recent_samples(self):
        threshold = timezone.now() - timedelta(days=7)
        return self.samples.filter(created_at__gte=threshold)

    @property
    def last_upload_at(self):
        if sample := self.samples.order_by('-id').first():
            return sample.created_at

    @property
    def is_valid(self):
        return self.start_at and self.end_at

    @property
    def is_in_progress(self):
        if self.is_valid:
            now = timezone.now()
            return now > self.start_at and now <= self.end_at

    @property
    def is_complete(self):
        if self.is_valid:
            now = timezone.now()
            return now > self.end_at

    @property
    def is_pending(self):
        if self.is_valid:
            now = timezone.now()
            return now < self.start_at

    @property
    def is_sharing(self):
        other_concurrent_observations = Observation.objects.filter(
            start_at__lte=self.end_at,
            end_at__gte=self.start_at,
            telescopes__in=self.telescopes.all()
        ).exclude(id=self.id)
        return other_concurrent_observations.exists()

app/rtshare/telescope/models.py
from datetime import timedelta

from django.conf import settings
from django.core.files.storage import storages
from django.db import models
from django.utils import timezone

from observations.models import Sample, Configuration
from rtshare.utils.models import BaseModel


def get_storage():
    return (
        storages['default']
        if settings.DEBUG else
        storages['remote']
    )


class Telescope(BaseModel):

    class Status:
        ACTIVE = 'active'
        INACTIVE = 'inactive'

        choices = (
            (ACTIVE, 'Active'),
            (INACTIVE, 'Inactive'),
        )

    class State:
        ONLINE = 'online'
        OFFLINE = 'offline'

        choices = (
            (ONLINE, 'Online'),
            (OFFLINE, 'Offline'),
        )

    name = models.CharField(
        max_length=256,
        help_text=(
            'The human-recognizable name for the device.'
        )
    )

    description = models.TextField(
        default='',
        blank=True,
        help_text=(
            'Any helpful text for the user of this device.'
        )
    )

    groups = models.ManyToManyField(
        'auth.Group',
    )

    latitude = models.DecimalField(
        max_digits=20,
        decimal_places=17,
        blank=True,
        null=True,
        default=None,
        help_text=(
            'The device\'s current latitude.'
        )
    )

    longitude = models.DecimalField(
        max_digits=20,
        decimal_places=17,
        blank=True,
        null=True,
        default=None,
        help_text=(
            'The device\'s current longitude.'
        )
    )

    elevation = models.IntegerField(
        default=0,
        help_text=(
            'The device\'s current elevation above sea level.'
        )
    )

    status = models.CharField(
        max_length=30,
        choices=Status.choices,
        default=Status.INACTIVE,
        help_text=(
            'The status of the device and whether it is actively being used.'
        )
    )

    state = models.CharField(
        max_length=30,
        choices=State.choices,
        default=State.OFFLINE,
        help_text=(
            'The current state of the device as reported by that device.'
        )
    )

    state_updated_at = models.DateTimeField(
        default=None,
        blank=True,
        null=True,
        help_text=(
            'The exact time when the state was last updated.'
        ),
    )

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.name} ({self.id})'

    @property
    def public_id(self):
        return f'TEL-{self.id}'

    @property
    def current_location(self):
        return self.latitude, self.longitude

    @property
    def is_active(self):
        return self.status == self.Status.ACTIVE

    @property
    def is_online(self):
        return self.state == self.State.ONLINE

    @property
    def user_channels(self):
        return [
            f'U-{user.id}'
            for group in self.groups.all()
            for user in group.user_set.all()
        ]

    @property
    def recent_observations(self):
        threshold = timezone.now() - timedelta(days=7)
        return self.observations.filter(start_at__gte=threshold, end_at__lte=timezone.now())

    @property
    def last_upload_at(self):
        qs = Sample.objects.filter(
            observation__in=self.observations.all()
        ).order_by('-id').first()

        if sample := qs:
            return sample.created_at

    @property
    def tasks(self):
        yesterday = timezone.now() - timedelta(days=1)
        return (
            Configuration.objects
            .filter(observation__telescopes=self)
            .filter(observation__end_at__gte=yesterday)
        )

app/rtshare/telescope/templates/configuration-detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load django_bootstrap5 %}

{% block subtitle %}Configuration {{ configuration.name }} | {% endblock %}

{% block content %}
<turbo-frame id="content" target="_top">
  <div class="d-flex align-items-center gap-3 justify-content-between border-bottom mb-3 pb-1">
    <h1>
      Configuration
      <small class="text-muted">| {{ configuration.name }}</small>
    </h1>
  </div>
  <div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-8 mb-3">
      <div class="card card-body mb-3">
        <h5>
          Observation
          <small class="text-muted">
            | {{ configuration.observation.name }}
          </small>
        </h5>
        <div class="border-start ps-2">
          <div>
            {{ configuration.observation.start_at|date:"SHORT_DATETIME_FORMAT" }} -
            {{ configuration.observation.end_at|date:"SHORT_DATETIME_FORMAT" }}
          </div>
          <div>
            {% for telescope in configuration.observation.telescopes.all %}
              {{ telescope.name }}{% if not forloop.last %},{% endif %}
            {% empty %}
              <i class="text-muted">
                No telescopes configured for this observation
              </i>
            {% endfor %}
          </div>
        </div>
      </div>
      <form action="{% url 'configuration.update' configuration.id %}" method="post">
        {% csrf_token %}
        <fieldset
          {% if not perms.configuration.change_configuration %}disabled{% endif %}
          {% if not configuration.observation.is_pending %}disabled{% endif %}
        >
          {% bootstrap_form form %}
        </fieldset>
        <div class="d-flex justify-content-end">
          <button
            class="btn btn-primary"
            type="submit"
            {% if not perms.configuration.change_configuration %}disabled{% endif %}
            {% if not configuration.observation.is_pending %}disabled{% endif %}
          >
            <i class="fa fa-save"></i>
            Save
          </button>
        </div>
      </form>
    </div>
    {% if configuration %}
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card card-body mb-3">
        <h3 class="border-bottom pb-1">
          Actions
        </h3>
        <div class="d-flex flex-column gap-2">
          {% if perms.configuration.view_observation %}
          <a
            href="{% url 'observation.update' configuration.observation.id %}"
            class="btn btn-sm btn-secondary"
          >
            <i class="fa fa-calendar-days"></i>
            Go to Observation
          </a>
          {% else %}
          <button
            class="btn btn-sm btn-secondary"
            disabled
          >
            <i class="fa fa-calendar-days"></i>
            Go to Observation
          </button>
          {% endif %}
        </div>
      </div>
    </div>
    {% endif %}
    </div>
</turbo-frame>
{% endblock %}

{% block morescript %}
<script>
  function setCurrentLocation() {
    navigator.geolocation.getCurrentPosition(position => {
      const { latitude, longitude } = position.coords;
      $('input[name="latitude"]').val(latitude);
      $('input[name="longitude"]').val(longitude);
    });
  }
</script>
{% endblock %}

app/rtshare/telescope/templates/telescope-detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load django_bootstrap5 %}

{% block subtitle %}Telescope {{ telescope.name }} | {% endblock %}

{% block content %}
<turbo-frame id="content" target="_top">
  <div class="d-flex align-items-center gap-3 justify-content-between border-bottom mb-3 pb-1">
    <h1>
      Telescope
      <small class="text-muted">| {{ telescope.name }}</small>
    </h1>
    <div>
      <span
        class="
          badge
          {% if telescope.is_active %}bg-primary{% else %}bg-secondary{% endif %}
        "
      >
        {{ telescope.get_status_display }}
      </span>
      <span
        class="
          badge
          {% if telescope.is_online %}bg-success{% else %}bg-secondary{% endif %}
        "
      >
        {{ telescope.get_state_display }}
      </span>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-8 mb-3">
      <form action="." method="post">
        {% csrf_token %}
        <fieldset
          {% if not perms.telescope.change_telescope %}disabled{% endif %}
        >
          {% bootstrap_form form %}
        </fieldset>
        <div class="d-flex justify-content-between">
          <button
            type="button"
            class="btn btn-secondary"
            onclick="setCurrentLocation()"
            {% if not perms.telescope.change_telescope %}disabled{% endif %}
          >
            <i class="fa fa-globe"></i>
            Set Current Location
          </button>
          <button
            class="btn btn-primary"
            type="submit"
            {% if not perms.telescope.change_telescope %}disabled{% endif %}
          >
            <i class="fa fa-save"></i>
            Save
          </button>
        </div>
      </form>
    </div>
    {% if telescope %}
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card card-body mb-3">
        <h3 class="border-bottom pb-1">
          Actions
        </h3>
        <form
          action="{% url 'telescope.ping' telescope.id %}"
          method="post"
          class="mb-1"
          id="send-test-event-form"
        >
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ telescope.id }}">
        </form>
        <form
          action="{% url 'telescope.reconfigure' telescope.id %}"
          method="post"
          class="mb-1"
          id="send-reconfigure-event-form"
        >
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ telescope.id }}">
        </form>
        <div class="d-flex flex-column gap-2">
          <button
            type="submit"
            class="btn btn-sm btn-secondary"
            form="send-test-event-form"
            {% if not perms.telescope.change_telescope %}disabled{% endif %}
          >
            <i class="fa fa-exclamation-circle"></i>
            Send Ping
          </button>
          <button
            type="submit"
            class="btn btn-sm btn-secondary"
            form="send-reconfigure-event-form"
            {% if not perms.telescope.change_telescope %}disabled{% endif %}
          >
            <i class="fa fa-gear"></i>
            Send Reconfigure
          </button>
          {% if perms.telescope.view_observation %}
          <a
            href="{% url 'telescope.observation-list' telescope.id %}"
            class="btn btn-sm btn-secondary"
          >
            <i class="fa-solid fa-calendar-days"></i>
            Browse Observations
          </a>
          {% else %}
          <button
            href=""
            class="btn btn-sm btn-secondary"
            disabled
          >
            <i class="fa fa-file"></i>
            Browse Observations
          </button>
          {% endif %}
        </div>
      </div>
      {% if request.user.is_staff %}
      <div class="card card-body mb-3">
        <h3 class="border-bottom mb-3 pb-1">
          Device Configuration
        </h3>
        <b>Telescope ID</b>
        <div class="p-3 mb-1 bg-light rounded">
          <code class="d-block">
            {{ telescope.id }}
          </code>
        </div>
        <b>Public ID</b>
        <div class="p-3 mb-1 bg-light rounded">
          <code class="d-block">
            {{ telescope.public_id }}
          </code>
        </div>
        <small>
          Use these values to configure the telescope so that it can send/receive data properly.
        </small>
      </div>
      {% endif %}
      <div class="card card-body">
        <h3 class="border-bottom mb-3 pb-1">
          More Information
        </h3>
        <ul>
          <li>
            {{ telescope.observations.count|default:0|intcomma }} total
            observation{{ telescope.observations.count|pluralize }}
          </li>
          <li>
            {{ telescope.recent_observations.count|default:0|intcomma }}
            observation{{ telescope.recent_observations.count|pluralize }}  this week
          </li>
          <li>
            {% if telescope.state_updated_at %}
              {{ telescope.state_updated_at|timesince }} since last state update
            {% else %}
              Never updated
            {% endif %}
          </li>
          <li>
            {% if telescope.last_upload_at %}
              {{ telescope.last_upload_at|timesince }} since last upload
            {% else %}
              Never updated
            {% endif %}
          </li>
          <li>
            {{ telescope.created_at|date }}
            (Created)
          </li>
          <li>
            {{ telescope.created_at|date }}
            (Last Updated)
          </li>
        </ul>
      </div>
    </div>
    {% endif %}
    </div>
</turbo-frame>
{% endblock %}

{% block morescript %}
<script>
  function setCurrentLocation() {
    navigator.geolocation.getCurrentPosition(position => {
      const { latitude, longitude } = position.coords;
      $('input[name="latitude"]').val(latitude);
      $('input[name="longitude"]').val(longitude);
    });
  }
</script>
{% endblock %}

app/rtshare/telescope/templates/telescope-list.html
{% extends 'base.html' %}

{% block content %}
<turbo-frame id="content" target="_top">
  <h1>
    All Telescopes
  </h1>
  <p>
    {% lorem %}
  </p>
  {% for telescope in object_list %}
  <div class="card card-body mb-2 position-relative">
    <h2>
      {{ telescope.name }}
    </h2>
    <div class="my-1">
       {{ telescope.get_status_display }}, {{ telescope.get_state_display }}
    </div>
    <a class="stretched-link" href="{% url 'telescope.update' telescope.id %}"></a>
  </div>
  {% empty %}


  {% endfor %}
</turbo-frame>
{% endblock %}

app/rtshare/telescope/templates/telescope-observation-list.html
{% extends 'base.html' %}
{% load humanize %}
{% load django_bootstrap5 %}

{% block subtitle %}Telescope {{ telescope.name }} Observations | {% endblock %}

{% block content %}
<turbo-frame id="content" target="_top">
  <div class="d-flex align-items-center gap-3 justify-content-between border-bottom mb-3 pb-1">
    <h1>
      Telescope
      <small class="text-muted">| {{ telescope.name }}</small>
    </h1>
    <div>
      <span
        class="
          badge
          {% if telescope.is_active %}bg-primary{% else %}bg-secondary{% endif %}
        "
      >
        {{ telescope.get_status_display }}
      </span>
      <span
        class="
          badge
          {% if telescope.is_online %}bg-success{% else %}bg-secondary{% endif %}
        "
      >
        {{ telescope.get_state_display }}
      </span>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12 col-md-6 col-lg-8">
      <h2>
        Observations
      </h2>
      <p>
        This table contains the list of observations available for this telescope.
      </p>
      <div class="list-group list-group-flush">
        {% for observation in observations %}
          {% include 'components/observation-list-item.html' %}
        {% empty %}
        <div class="list-group-item">
          <i class="text-muted">Nothing to show</i>
        </div>
        {% endfor %}
      </div>
      <nav aria-label="Observation Pagination">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; First</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item">
            <span class="page-link current text-black">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    {% if telescope %}
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card card-body mb-3">
        <h3 class="border-bottom pb-1">
          Actions
        </h3>
        <div class="d-flex flex-column gap-2">
          <a
            href="{% url 'telescope.update' telescope.id %}"
            class="btn btn-sm btn-secondary"
          >
            Go to Telescope
          </a>
        </div>
      </div>
      <div class="card card-body">
        <h3 class="border-bottom mb-3 pb-1">
          More Information
        </h3>
        <ul>
          <li>
            {{ telescope.observations.count|default:0|intcomma }} total observations
          </li>
          <li>
            {{ telescope.recent_observations.count|default:0|intcomma }} observations this week
          </li>
          <li>
            {% if telescope.last_upload_at %}
              {{ telescope.last_upload_at|timesince }} since last upload
            {% else %}
              Unknown status
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
    {% endif %}
  </div>
</turbo-frame>
{% endblock %}

{% block morescript %}
<script>
  function setCurrentLocation() {
    navigator.geolocation.getCurrentPosition(position => {
      const { latitude, longitude } = position.coords;
      $('input[name="latitude"]').val(latitude);
      $('input[name="longitude"]').val(longitude);
    });
  }
</script>
{% endblock %}